### ISSUE TITLE
AffineTransform multiplication test failed once

### ISSUE THREAD

**Issue by jlfwong** [jlfwong/speedscope#138]
From: https://travis-ci.org/jlfwong/speedscope/builds/416911664?utm_source=github_status&utm_medium=notification

```
 FAIL  src/lib/math.test.ts (42.845s)
  ● AffineTransform › times
    Failed after 62 tests and 55 shrinks. rngState: 8394d7fb8c61ae2305; Counterexample: {"m00":0,"m01":-5.367341258943892e-7,"m02":0,"m10":-5.637762076626807e-7,"m11":22.105444583576173,"m12":0}; {"m00":-19.956948631443083,"m01":41.27141907811165,"m02":32.4375735828653,"m10":-19.53049001749605,"m11":40.38256627973169,"m12":3.136250004172325}; 
      359 | 
      360 |   test('times', () => {
    > 361 |     jsc.assertForall(invertibleTransform, invertibleTransform, (t1, t2) => {
          |         ^
      362 |       return t1
      363 |         .times(t2)
      364 |         .times(t2.inverted()!)
      at node_modules/jsverify/lib/jsverify.js:360:15
      at Object.map (node_modules/jsverify/lib/functor.js:35:12)
      at checkThrow (node_modules/jsverify/lib/jsverify.js:354:30)
      at Object.assertForall (node_modules/jsverify/lib/jsverify.js:485:10)
      at Object.test (src/lib/math.test.ts:361:9)
```

**Comment by jlfwong** [comment]
I hit this again:

```
    Failed after 36 tests and 57 shrinks. rngState: 857c059d36a1824bef; Counterexample: {"m00":0,"m01":7.101930074443485e-7,"m02":0,"m10":-5.378125217531116e-7,"m11":2.90428925357
99183,"m12":0}; {"m00":12.973272448405623,"m01":7.433900397270918,"m02":-21.513099929783493,"m10":36.96676528733224,"m11":21.18127042800188,"m12":28.690610187128186};

      342 |
      343 |   test('times', () => {
    > 344 |     jsc.assertForall(invertibleTransform, invertibleTransform, (t1, t2) => {
          |         ^
      345 |       return t1.times(t2).times(t2.inverted()!).approxEquals(t1)
      346 |     })
      347 |   })

      at node_modules/jsverify/lib/jsverify.js:360:15
      at Object.map (node_modules/jsverify/lib/functor.js:35:12)
      at checkThrow (node_modules/jsverify/lib/jsverify.js:354:30)
      at Object.assertForall (node_modules/jsverify/lib/jsverify.js:485:10)
      at Object.test (src/lib/math.test.ts:344:9)
```
