### ISSUE TITLE
`npm install` fails on node.js 13

### ISSUE THREAD

**Issue by JustinBeckwith** [jlfwong/speedscope#262]
Greetings!  I tried to clone the repository, and run `npm install` with the latest release of node.js 13.x.  The install fails:

```
$ node -v
v13.13.0

$ npm install
<.... lots of errors ....>
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: 
      expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
17 errors generated.
make: *** [deasync.target.mk:131: Release/obj.target/deasync/src/deasync.o] Error 1
make: Leaving directory '/Users/beckwith/Code/speedscope/node_modules/deasync/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/beckwith/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/beckwith/.nvm/versions/node/v13.13.0/bin/node" "/Users/beckwith/.nvm/versions/node/v13.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/beckwith/Code/speedscope/node_modules/deasync
gyp ERR! node -v v13.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/chokidar/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.13 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deasync@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/beckwith/.npm/_logs/2020-04-19T21_59_15_064Z-debug.log
speedscope (master) $ 
```

The culprit appears to be `fs-events` doing native compilation and missing binaries for the specific version of node.  The issue appears to be resolved by using the latest version of `jest` (which comes with its own challenges).

**Comment by JustinBeckwith** [comment]
Thank you so much for the fix!
